-- Chercher Steve McQueen
-- Chercher Tarantino
-- Chercher les gens dont le nom finit par O'Hara
-- Les personnes nées en 1930 triées par ordre alphabétique
-- Quel age aura Clint Estwood à la fin de l'année ?
-- les films des années 70s durant entre 2H et 2H10 
--		triés par durée décroissante puis par titre
-- Combien y a t il de Steve McQueen ?
-- Combien y a t il de noms différents de personne ? 
-- 		Combien sont répétés ?
